/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Controladores.traerJson;
import static Controladores.traerJson.getRegistros;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.json.JSONArray;
import org.json.JSONObject;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author cmadrid
 */
public class formHome extends javax.swing.JFrame {
    private JPanel panelChartPanel1;
    traerJson getData = new traerJson();
    String jsonRegistros = traerJson.getRegistros();
    JSONArray jsonArray = new JSONArray(jsonRegistros);
    /**
     * Creates new form formHome
     */
    public formHome() {
        initComponents();
        // Asegúrate de que panelContenedor se inicialice antes de llamar a generarGraficaGanancias
        panelChartPanel1 = new JPanel();
        panelChartPanel1.setLayout(new BorderLayout());
        getContentPane().add(panelChartPanel1, BorderLayout.CENTER);
        generarGraficaGanancias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Ponentes = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TICKETSALES");

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Reportes TicketSales");

        jMenu1.setText("Usuarios Registrados");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Usuarios Confirmados");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Regalos");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        Ponentes.setText("Ponentes");
        Ponentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PonentesMouseClicked(evt);
            }
        });
        jMenuBar1.add(Ponentes);

        jMenu4.setText("Eventos");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1351, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addContainerGap(718, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
         try {
            // Establece el Look and Feel de FlatLaf
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Aquí es donde inicializarías y mostrarías tu JFrame principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUsuariosConfirmados().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        try {
            // Establece el Look and Feel de FlatLaf
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Aquí es donde inicializarías y mostrarías tu JFrame principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUsuarios().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        try {
            // Establece el Look and Feel de FlatLaf
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Aquí es donde inicializarías y mostrarías tu JFrame principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegalos().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenu2MouseClicked

    private void PonentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PonentesMouseClicked
        // TODO add your handling code here:
        try {
            // Establece el Look and Feel de FlatLaf
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Aquí es donde inicializarías y mostrarías tu JFrame principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPonentes().setVisible(true);
            }
        });
    }//GEN-LAST:event_PonentesMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
         try {
            // Establece el Look and Feel de FlatLaf
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Aquí es donde inicializarías y mostrarías tu JFrame principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEventos().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formHome().setVisible(true);
            }
        });
    }
    
     private void generarGraficaGanancias() {
        // Tu código para procesar el JSON y calcular ganancias
        int gananciasPaquete1 = 0;
        int gananciasPaquete2 = 0;
        for (int i = 0; i < jsonArray.length(); i++) {
            JSONObject obj = jsonArray.getJSONObject(i);
            int paqueteId = obj.optInt("paquete_id");
            if (paqueteId == 1) {
                gananciasPaquete1 += 199;
            } else if (paqueteId == 2) {
                gananciasPaquete2 += 49;
            }
        }
        
        // Crear dataset y gráfico
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Paquete virtual $" + gananciasPaquete1, gananciasPaquete1);
        dataset.setValue("Paquete virtual $" + gananciasPaquete2, gananciasPaquete2);


        // Crear gráfica de pastel
        JFreeChart pieChart = ChartFactory.createPieChart(
                "Ganancias por Paquete",
                dataset,
                true, true, false);
        
        panelChartPanel1 = new ChartPanel(pieChart);
        panelChartPanel1.setBounds(10, 100, 1350, 600); // Ajustar las dimensiones según sea necesario

        // Agregar el ChartPanel al JFrame
        // Limpiar el panelContenedor
        getContentPane().add(panelChartPanel1);
        getContentPane().revalidate();
        getContentPane().repaint();

         
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ponentes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
